### ISSUE TITLE
Bug: Calling the plot3D method results in the script crashing

### ISSUE THREAD

**Issue by Kyr27** [nbhr/geodome#1]
**Type**: Bug

**Description**:
I downloaded the geodome script and installed all the necessary libraries using python 3.12, however any attempt at running the plot3D method results in a crash, nothing was modified in the script.

**Steps to Reproduce:**
Download the geodome.py file from this repository and run it

**Expected Behavior:**
A window with the 3D representation of the geodesic dome inside it should show.

**Actual Behavior:**
Script crashes

**Logs:**
Traceback (most recent call last):
  File "C:\Users\MAUS\Downloads\geodome.py", line 154, in <module>
    g.plot3D()
  File "C:\Users\MAUS\Downloads\geodome.py", line 76, in plot3D
    tri = Poly3DCollection(self.v[self.f].reshape((-1, 3)))
  File "C:\Users\MAUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpl_toolkits\mplot3d\art3d.py", line 924, in __init__
    raise ValueError('verts must be a list of (N, 3) array-like')
ValueError: verts must be a list of (N, 3) array-like

**Environment:**
Windows 10 Home, Version 22H2
Python version: 3.12.7

**Comment by nbhr** [comment]
Thank you for pointing this out.  I have merged your PR.
